# Generated by Django 5.2.6 on 2025-10-30 01:52

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#667eea",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Protocol Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "protocol_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique protocol identifier (e.g., SOP-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief overview of the protocol"
                    ),
                ),
                (
                    "objective",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Purpose and goals of this protocol"
                    ),
                ),
                (
                    "materials",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Required materials, equipment, and reagents",
                    ),
                ),
                (
                    "procedure",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Step-by-step instructions"
                    ),
                ),
                (
                    "safety_notes",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Safety precautions and warnings"
                    ),
                ),
                (
                    "troubleshooting",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Common issues and solutions"
                    ),
                ),
                (
                    "references",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Citations and related protocols"
                    ),
                ),
                (
                    "notes",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Additional notes and comments"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Protocol version number"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active version for use"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "times_used",
                    models.IntegerField(
                        default=0, help_text="Number of experiments using this protocol"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocols_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_protocol",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original protocol if this is a version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="protocols.protocol",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocols",
                        to="protocols.protocolcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("protocol_code", "version")},
            },
        ),
    ]
