# Generated by Django 5.2.6 on 2025-10-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="protocol",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="protocol_code",
            field=models.CharField(
                blank=True,
                help_text="Unique protocol identifier (e.g., SOP-001)",
                max_length=50,
            ),
        ),
    ]
