# Generated by Django 5.2.6 on 2025-09-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="sample_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
