# Generated by Django 5.2.6 on 2025-10-07 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0002_alter_sample_sample_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuantityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("USE", "Used in experiment"),
                            ("ADD", "Quantity added"),
                            ("ADJUST", "Manual adjustment"),
                            ("SPLIT", "Split into aliquots"),
                            ("DISPOSE", "Disposed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "quantity_change",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "quantity_after",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quantity_logs",
                        to="samples.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
