# Generated by Django 5.2.6 on 2025-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0003_quantitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="expiration_date",
            field=models.DateField(
                blank=True, help_text="Date when sample expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="min_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Minimum quantity before low stock alert",
                max_digits=10,
                null=True,
            ),
        ),
    ]
