# Generated by Django 5.2.6 on 2025-10-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0004_sample_expiration_date_sample_min_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="derivation_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about how this sample was created from parent",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="parent_sample",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent sample if this is an aliquot or derivative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_samples",
                to="samples.sample",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ALIQUOT", "Aliquot - portion of parent"),
                    ("DERIVATIVE", "Derivative - processed from parent"),
                    ("SPLIT", "Split - equal division of parent"),
                ],
                help_text="Type of relationship to parent sample",
                max_length=20,
                null=True,
            ),
        ),
    ]
